# Generated by Django 5.2.14 on 2026-05-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_galleryorderevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryorderevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='galleryorderevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
